module.exports = {
  root: true,
  // stylelint插件 -- （指定css属性顺序的插件）
  plugins: ['stylelint-order'],
  // 继承拓展现有配置 （stylelint-config-prettier：会检查与prettier的冲突，所有要放在后面他会覆盖前面规则）
  extends: ['stylelint-config-standard', 'stylelint-config-prettier'],
  // 规则
  rules: {
    // 禁止未知的伪类选择器
    'selector-pseudo-class-no-unknown': [
      true,
      {
        // 忽略的伪类
        ignorePseudoClasses: ['global'],
      },
    ],
    // 禁止未知的伪元素选择器
    'selector-pseudo-element-no-unknown': [
      true,
      {
        // 忽略的伪元素
        ignorePseudoElements: ['v-deep'],
      },
    ],
    // 禁止未知的规则
    'at-rule-no-unknown': [
      true,
      {
        // 忽略不被违规的选项
        ignoreAtRules: ['function', 'if', 'each', 'include', 'mixin'],
      },
    ],
    // 禁止空来源
    'no-empty-source': null,
    // 禁止无效的命名区域 例如：a { color: "" }
    'named-grid-areas-no-invalid': null,
    // 禁止unicode标记
    'unicode-bom': 'never',
    // 禁止低优先级的选择器出现在高优先级选择器后面
    'no-descending-specificity': null,
    // 禁止在字体系列中缺少通用的系列
    'font-family-no-missing-generic-family-keyword': null,
    // 冒号之后后需要一个空格，如果是单行的
    'declaration-colon-space-after': 'always-single-line',
    // 冒号之前需要一个空格：从不
    'declaration-colon-space-before': 'never',
    // 要求或禁止在声明块中使用尾随分号。
    'declaration-block-trailing-semicolon': 'always',
    // 要求或禁止规则前的空行。
    'rule-empty-line-before': [
      'always',
      {
        // 忽略
        ignore: ['after-comment', 'first-nested'],
      },
    ],
    // 禁止未知单位
    'unit-no-unknown': [true, { ignoreUnits: ['rpx'] }],
    'order/order': [
      [
        // 不允许在样式表中使用美元变量
        'dollar-variables',
        // 自定义属性
        'custom-properties',
        'at-rules',
        'declarations',
        {
          type: 'at-rule',
          name: 'supports',
        },
        {
          type: 'at-rule',
          name: 'media',
        },
        'rules',
      ],
      { severity: 'warning' },
    ],
    // 按照指定顺序排列
    'order/properties-order': [
      'position',
      'content',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      'float',
      'width',
      'height',
      'max-width',
      'max-height',
      'min-width',
      'min-height',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'margin-collapse',
      'margin-top-collapse',
      'margin-right-collapse',
      'margin-bottom-collapse',
      'margin-left-collapse',
      'overflow',
      'overflow-x',
      'overflow-y',
      'clip',
      'clear',
      'font',
      'font-family',
      'font-size',
      'font-smoothing',
      'osx-font-smoothing',
      'font-style',
      'font-weight',
      'hyphens',
      'src',
      'line-height',
      'letter-spacing',
      'word-spacing',
      'color',
      'text-align',
      'text-decoration',
      'text-indent',
      'text-overflow',
      'text-rendering',
      'text-size-adjust',
      'text-shadow',
      'text-transform',
      'word-break',
      'word-wrap',
      'white-space',
      'vertical-align',
      'list-style',
      'list-style-type',
      'list-style-position',
      'list-style-image',
      'pointer-events',
      'cursor',
      'background',
      'background-attachment',
      'background-color',
      'background-image',
      'background-position',
      'background-repeat',
      'background-size',
      'border',
      'border-collapse',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-color',
      'border-image',
      'border-top-color',
      'border-right-color',
      'border-bottom-color',
      'border-left-color',
      'border-spacing',
      'border-style',
      'border-top-style',
      'border-right-style',
      'border-bottom-style',
      'border-left-style',
      'border-width',
      'border-top-width',
      'border-right-width',
      'border-bottom-width',
      'border-left-width',
      'border-radius',
      'border-top-right-radius',
      'border-bottom-right-radius',
      'border-bottom-left-radius',
      'border-top-left-radius',
      'border-radius-topright',
      'border-radius-bottomright',
      'border-radius-bottomleft',
      'border-radius-topleft',
      'quotes',
      'outline',
      'outline-offset',
      'opacity',
      'filter',
      'visibility',
      'size',
      'zoom',
      'transform',
      'box-align',
      'box-flex',
      'box-orient',
      'box-pack',
      'box-shadow',
      'box-sizing',
      'table-layout',
      'animation',
      'animation-delay',
      'animation-duration',
      'animation-iteration-count',
      'animation-name',
      'animation-play-state',
      'animation-timing-function',
      'animation-fill-mode',
      'transition',
      'transition-delay',
      'transition-duration',
      'transition-property',
      'transition-timing-function',
      'background-clip',
      'backface-visibility',
      'resize',
      'appearance',
      'user-select',
      'interpolation-mode',
      'direction',
      'marks',
      'page',
      'set-link-source',
      'unicode-bidi',
      'speak',
    ],
  },
  ignoreFiles: ['**/*.js', '**/*.jsx', '**/*.tsx', '**/*.ts'],
};
